notifications:
  email: false
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python3 setup.py
# command to run tests
script: 
  - pytest